### ISSUE TITLE
justify csv for tabular view

### ISSUE THREAD

**Issue by people-can-fly** [mechatroner/sublime_rainbow_csv#10]

**Comment by mechatroner** [comment]
Do you mean align with spaces so all entries in a column take up the same number of characters?

**Comment by gregsadetsky** [comment]
I'm not sure if that was the feature request, but your suggestion is a great idea! :-) Cheers

**Comment by mechatroner** [comment]
Done: new version 1.3 has "Align" command which will indent columns by inserting additional whitespaces. And "Shrink" command can be used to remove them.
