### ISSUE TITLE
Plugin still shows popups after switched to plain text

### ISSUE THREAD

**Issue by dmi7ry** [mechatroner/sublime_rainbow_csv#13]
I open a file and plugin automatically detects it as `CSV (Rainbow)`. Then I switch mode to `Plain text`.
But it still shows popups:
![popup](https://user-images.githubusercontent.com/1731751/53153256-65ea8b00-35ea-11e9-942a-dc216274471f.png)

**Comment by mechatroner** [comment]
Fixed in 1.2.1
