### ISSUE TITLE
Incorrect color scheme global setting names

### ISSUE THREAD

**Issue by srbs** [mechatroner/sublime_rainbow_csv#16]
The `globals` color scheme key names should be snake_case, not camelCase. i.e. `lineHighlight` should be `line_highlight` here: https://github.com/mechatroner/sublime_rainbow_csv/blob/master/RainbowCSV.sublime-color-scheme#L8-L19

**Comment by mechatroner** [comment]
Thanks again! I've just published fixed version: 1.1.1
