### ISSUE TITLE
| 'pipe' separator auto-detection not working

### ISSUE THREAD

**Issue by tomapirin** [mechatroner/sublime_rainbow_csv#17]
Hello,
first of all, thank you for this FANTASTIC Sublime package, it saves me a great deal of time analysing csv files. 
It worked seamless opening files with 'comma' delimiter. When we changed to 'pipe' separator it did not auto-detect it. 

I have upgraded Sublime and the package to latest version.
**Sublime Text v3.2
sublime_rainbow_csv v1.1.1**

I have tried to change user settings with no success. "enable_rainbow_csv_autodetect": true/false. If I manually set separator in menu "Enable standard" or "Enable simple". It highlights the repeated re-open of file. But for every new csv file I have to set it manually again, and I deal with a lot of files.

Could this be somehow defined in settings, or simply changed in application code? If not, could it be fixed?

Issue example
![image](https://user-images.githubusercontent.com/7482903/55401474-28fea600-5551-11e9-849d-0a373eef32c8.png)

**Comment by mechatroner** [comment]
Hi @tomapirin,
Thank you very much for the feedback!
Sure, this is easy to implement. I will include this feature in the next release.

**Comment by tomapirin** [comment]
Hi @mechatroner, 
when is the next release expected?

**Comment by mechatroner** [comment]
I will try to publish it on Friday this week

**Comment by mechatroner** [comment]
Implemented in 1.2.1

**Comment by mechatroner** [comment]
This config line should do the trick:
```
"rainbow_csv_autodetect_dialects": [["\t", "simple"], [",", "quoted"], [";", "quoted"], ["|", "simple"]]
```
Please let me know if it doesn't work or if there are some other issues!

**Comment by tomapirin** [comment]
Great job, works perfectly!
