### ISSUE TITLE
PSV support

### ISSUE THREAD

**Issue by inoto** [mechatroner/sublime_rainbow_csv#18]
Can you add support for PSV (pipe-separated) too? Or is it possible to have setting where we can list custom extensions to apply rainbow color scheme?
Currently I have PSV and I want to automatic apply rainbow mode on file open.

**Comment by mechatroner** [comment]
Actually, I've added pipe separated files autodetection in version 1.3.0, so it should work out of the box, if your file is at least 8 lines and has constant number of pipes per line. If it doesn't work for your file for some reason, please post it's content here with sensitive data removed.
Also you can use built-in sublime mechanism to associate .psv extension with "Rainbow csv pipe Simple" dialect:
View -> Syntax -> Open all with current extension as ... -> rainbow_csv -> Rainbow csv pipe Simple
https://stackoverflow.com/a/8104764/2898283

**Comment by inoto** [comment]
Yeah, I had v1.2.1 and now it works from the box when updated to v1.3.0. Thanks.
It would be great to add info that pipe-separated could be detected automatically (mention in settings or in README).
