### ISSUE TITLE
Does this plugin support multiline column?

### ISSUE THREAD

**Issue by o3661606** [mechatroner/sublime_rainbow_csv#20]
Does this plugin support multiline within a column?

I have a csv looks like this, which col_B contains multiline content enclosed by quote: 
> col_A, col_B, col_C
apple,"normal text", 12.5
banana, "This is
multi-line
content", 14
watermelon,text,20

When parsed by this plugin, it shows me "This line has quoting error"

**Comment by mechatroner** [comment]
Multiline fields are currently not supported. I will need to investigate if Sublime syntax engine allows to support them, and if it does, this feature can be added. I will post an update.

**Comment by mechatroner** [comment]
Multiline field support was added in version 2.3.0. 
To enable multiline fields you need to set `"allow_newlines_in_fields": true` in the config. 
If everything goes well I will think about enabling this by default in future releases. 
@o3661606, please let me know if something is not working as you expected.

**Comment by 122800** [comment]
Hello,

This feature didn't seem to work for me at first, so I went digging around and found [this commit (5722aee - support quoted_rfc switch)](https://github.com/mechatroner/sublime_rainbow_csv/commit/5722aeed0e1388278ba61d2834e062cfe933aea1#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R59), which showed me that the line break handling is only enabled when the separator in use is `;` or `,` (I was using the pipe character `|`). Is there any reason why this restriction is applied for this feature to be enabled?

At first I thought that the feature was sticking strictly to the CSV definition in RFC-4180, but that officially defines only `,` as a separator, so this already doesn't seem to be the case.

**Comment by mechatroner** [comment]
@122800, it is not supported because I was thinking that there is no practical need for this. But your request shows that I was wrong and I just opened a new issue #35. It should be relatively easy to do, just delete the check here: https://github.com/mechatroner/sublime_rainbow_csv/blob/e2fa752e4bae3a16e226f038744f937e57b6834f/main.py#L464  and test that everything works as expected, the syntax generation logic should already support arbitrary separators.

**Comment by 122800** [comment]
Thanks for the tip, @mechatroner!
I can't guarantee that I'll have the time anytime soon to try this out, but if I get the chance I'll definitely let you know :)
