### ISSUE TITLE
Cannot run query on temporary buffer (i.e. unsaved file)

### ISSUE THREAD

**Issue by gregsadetsky** [mechatroner/sublime_rainbow_csv#24]
Hi,

Thank you for the wonderful extension, I use it very frequently and adore it!

I was wondering if the extension is supposed to work on unsaved files?

I sometimes copy and paste bits of CSV into a new Sublime window, and manually set the syntax to "CSV (Rainbow)". The auto coloring works, but I cannot execute queries. Every time I do, I get the following error:

"RBQL Error. Unable to run query for this buffer"

After saving the file to a temporary location, I'm able to execute queries. Is there a way that queries could be run on unsaved files?

Thank you very much!

**Comment by mechatroner** [comment]
Hi Greg,
I will probably code it the same way: save the unnamed buffer to a temporary file, then run the query against it. But it will be done automatically.

**Comment by mechatroner** [comment]
Done. This should work now starting from version 2.0.0
