### ISSUE TITLE
The settings file "res://Packages/rainbow_csv/RainbowCSV.sublime-settings" could not be opened

### ISSUE THREAD

**Issue by sgstokes** [mechatroner/sublime_rainbow_csv#26]
I followed the Package Control implementation, and restarted Sublime, but I continue to receive the following error:

The settings file "res://Packages/rainbow_csv/RainbowCSV.sublime-settings" could not be opened

What should I check?

**Comment by mechatroner** [comment]
When do you get this error (after what action)? Maybe you can try to uninstall and the install again?
I think this is an issue with ST3/Package control, not with Rainbow CSV itself. Could you please check Rainbow CSV install directory to make sure that "rainbow_csv" was really installed and RainbowCSV.sublime-settings is in it.

**Comment by sgstokes** [comment]
After I went through the following steps using Package Control: Add Repository> Install Package I am able to select sublime_rainbow_csv for the file type and further select one of many Rainbow CSV file types. That said, if I select Rainbow CSV>Settings from either the context menu or Preferences>Package Settings, I get the "The settings file "res://Packages/rainbow_csv/RainbowCSV.sublime-settings" could not be opened" error.

**Comment by mechatroner** [comment]
@sgstokes Sorry for late reply. Actually The first step "Add Repository" is redundant - "rainbow_csv" is listed in the default Sublime Package Control Channel. So you could actually try to delete the entry you have manually added by running "Package Control: Remove Repository". I suspect that you have installed "rainbow_csv" as "sublime_rainbow_csv" for some reason (but I can not reproduce this) and this is why the package can't find it's own settings. Could you please check your packages directory, go to `Preferences -> Browse Packages` to make sure that you have "rainbow_csv" folder there and not "sublime_rainbow_csv". If this is not the case, then I just have no idea how  "rainbow_csv/RainbowCSV.sublime-settings" could be missing.

**Comment by sgstokes** [comment]
That fixed it. Thank you!

**Comment by mechatroner** [comment]
You are welcome!
