### ISSUE TITLE
Align columns with spaces adds trailing spaces

### ISSUE THREAD

**Issue by Zetym** [mechatroner/sublime_rainbow_csv#28]
The alignment works nicely from the very limited testing I've done, but the final column is also processed for equal width with trailing spaces. This means that if one line is long enough for the final element to trigger a word wrap, every line becomes long enough to trigger a word wrap, which is both annoying and confusing as there doesn't seem to be any reason for it unless the user has whitespace shown

**Comment by mechatroner** [comment]
Hi @Zetym, Thanks for the bug report!
I will try to fix this in the next release

**Comment by mechatroner** [comment]
Fixed in 2.3.0
