### ISSUE TITLE
Option to start columns at 0

### ISSUE THREAD

**Issue by tcsi-github** [mechatroner/sublime_rainbow_csv#36]
We have other software at our company that reads CSVs as 0,1,2,3 rather than 1,2,3,4 

I love the extension, however, I haven't seen an option to start at 0 rather than 1. Is this possible now? If not can it be added as an option? 

I can't tell you how many times I've messed up something just forgetting mentally to -1 from the pop-up. 

Thanks for any consideration. :-)

![image](https://user-images.githubusercontent.com/97745859/163843064-631f33cb-c95c-4a12-81ee-12ded958b5db.png)

**Comment by mechatroner** [comment]
Great idea, thank you! I will add it as an option. I would also need to integrate it later with RBQL though so that when the mode is active the column names are zero-based i.e. `a0`, `a1`, etc

**Comment by tcsi-github** [comment]
Thank you so much for this. It is very appreciated! :-)

**Comment by mechatroner** [comment]
I added a new config parameter to support this. I also tried to update RBQL to support zero-based column addressing but it turned out to be harder than expected (although I essentially solved the problem, the resulting diff ended up significantly larger than I expected so I put it on hold for now)

**Comment by tcsi-github** [comment]
Thank you so much for your work on this!

**Comment by mechatroner** [comment]
You are welcome, And thanks for using the extension!
