### ISSUE TITLE
Long data problem

### ISSUE THREAD

**Issue by ramilsitdikov** [mechatroner/sublime_rainbow_csv#6]
![screen shot 2018-06-01 at 13 43 42](https://user-images.githubusercontent.com/7632551/40837084-d60064ec-65a1-11e8-9d82-9ab2d37ad038.png)

If data string is long plugin does not work good – no syntax highlight

**Comment by mechatroner** [comment]
Hi @ramilsitdikov Thank you very much for the bug report and sorry about late reply. This looks like Sublime Text regexp engine limitation. I will try to submit a bug report to Sublime Text team.

**Comment by piddubnyi** [comment]
Hi, I faced the problem which looks very similar.
Test file in attachement.

![image](https://user-images.githubusercontent.com/6010247/50641785-6743f380-0f69-11e9-9d9e-4ca9d5c3ba31.png)

[pdg-extarct.zip](https://github.com/mechatroner/sublime_rainbow_csv/files/2723984/pdg-extarct.zip)

**Comment by mechatroner** [comment]
I submitted a bug report to Sublime team: https://github.com/SublimeTextIssues/Core/issues/2647

**Comment by mechatroner** [comment]
Fixed in version 1.1.0
