### ISSUE TITLE
Light background

### ISSUE THREAD

**Issue by sdelquin** [mechatroner/sublime_rainbow_csv#7]
Is there any way to leave a light background when the .csv file is opened?

**Comment by mechatroner** [comment]
The only way to do it now is to manually install the extension from github and remove all the *.sublime-settings files and RainbowCSV.tmTheme file. Either that or customize the RainbowCSV.tmTheme file. At some point I will add the option to highlight with user color scheme by default and ability to customize colors, probably within the next few months.

**Comment by sdelquin** [comment]
Thanks for your reply!
