### ISSUE TITLE
rainbow csv crash on large files

### ISSUE THREAD

**Issue by philohistoria** [mechatroner/sublime_rainbow_csv#8]
I have constantly used rainbow CSV.
Some of files I am working with are over 100 MB. Rainbow CSV just make sublime crash. 
Is there a way to change the config file of Rainbow CSV, such that it will skip to interpret CSV files if it is over a size limit?

**Comment by mechatroner** [comment]
Hello!
Thanks for bug report and feature suggestion.
I've just published updated version 0.4.0, but it can take some time before it becomes available in Package Control.
New version supports "rainbow_csv_max_file_size_bytes" config option which should "fix" the problem. 

Please, leave a feedback if it works for you or not.
